export const organizationPolicies = {
  "org-1": [
    {
      id: "pol-1",
      name: "Базовый Linux Hardening",
      status: "Активна",
      owner: "Отдел ИБ",
      scope: "Серверы Linux",
      updatedAt: "2026-03-29",
    },
    {
      id: "pol-2",
      name: "Контроль паролей",
      status: "На пересмотре",
      owner: "GRC",
      scope: "Домен / IAM",
      updatedAt: "2026-03-27",
    },
  ],
  "org-2": [
    {
      id: "pol-3",
      name: "Политика PostgreSQL",
      status: "Активна",
      owner: "DBA + ИБ",
      scope: "Базы данных",
      updatedAt: "2026-03-30",
    },
    {
      id: "pol-4",
      name: "Hardening web-tier",
      status: "Черновик",
      owner: "InfraSec",
      scope: "Web / Reverse Proxy",
      updatedAt: "2026-03-25",
    },
  ],
  "org-3": [
    {
      id: "pol-5",
      name: "Банковский профиль CIS",
      status: "Активна",
      owner: "Security Governance",
      scope: "Критичные контуры",
      updatedAt: "2026-03-28",
    },
  ],
};

export const organizationReports = {
  "org-1": {
    score: 82,
    scans: 4,
    passed: 214,
    failed: 47,
    history: [
      {
        id: "scan-1",
        date: "2026-03-10",
        score: 68,
        failed: 81,
        formatPdf: true,
        formatXlsx: true,
      },
      {
        id: "scan-2",
        date: "2026-03-18",
        score: 74,
        failed: 62,
        formatPdf: true,
        formatXlsx: true,
      },
      {
        id: "scan-3",
        date: "2026-03-24",
        score: 79,
        failed: 53,
        formatPdf: true,
        formatXlsx: true,
      },
      {
        id: "scan-4",
        date: "2026-03-30",
        score: 82,
        failed: 47,
        formatPdf: true,
        formatXlsx: true,
      },
    ],
    diff: [
      {
        asset: "web-prod-01",
        rule: "SSH root login disabled",
        before: "fail",
        after: "pass",
        result: "Исправлено",
      },
      {
        asset: "db-core-01",
        rule: "Password expiration policy",
        before: "fail",
        after: "fail",
        result: "Не исправлено",
      },
      {
        asset: "jump-01",
        rule: "Auditd enabled",
        before: "pass",
        after: "fail",
        result: "Ухудшилось",
      },
    ],
  },
  "org-2": {
    score: 73,
    scans: 2,
    passed: 141,
    failed: 52,
    history: [
      {
        id: "scan-5",
        date: "2026-03-20",
        score: 69,
        failed: 61,
        formatPdf: true,
        formatXlsx: true,
      },
      {
        id: "scan-6",
        date: "2026-03-30",
        score: 73,
        failed: 52,
        formatPdf: true,
        formatXlsx: true,
      },
    ],
    diff: [
      {
        asset: "api-gw-01",
        rule: "TLS 1.0 disabled",
        before: "fail",
        after: "pass",
        result: "Исправлено",
      },
      {
        asset: "db-report-01",
        rule: "Remote access restriction",
        before: "fail",
        after: "fail",
        result: "Не исправлено",
      },
    ],
  },
  "org-3": {
    score: 88,
    scans: 3,
    passed: 322,
    failed: 21,
    history: [
      {
        id: "scan-7",
        date: "2026-03-05",
        score: 79,
        failed: 49,
        formatPdf: true,
        formatXlsx: true,
      },
      {
        id: "scan-8",
        date: "2026-03-17",
        score: 84,
        failed: 31,
        formatPdf: true,
        formatXlsx: true,
      },
      {
        id: "scan-9",
        date: "2026-03-30",
        score: 88,
        failed: 21,
        formatPdf: true,
        formatXlsx: true,
      },
    ],
    diff: [
      {
        asset: "core-bank-01",
        rule: "MFA enforcement",
        before: "fail",
        after: "pass",
        result: "Исправлено",
      },
    ],
  },
};

export const organizationProjects = {
  "org-1": [
    {
      id: "env-1",
      name: "Production",
      segment: "DMZ + Internal",
      assets: 18,
      critical: 7,
      status: "Под контролем",
    },
    {
      id: "env-2",
      name: "Test",
      segment: "Lab",
      assets: 8,
      critical: 1,
      status: "Ограниченный контур",
    },
  ],
  "org-2": [
    {
      id: "env-3",
      name: "Core Infrastructure",
      segment: "Datacenter",
      assets: 26,
      critical: 9,
      status: "Высокий приоритет",
    },
  ],
  "org-3": [
    {
      id: "env-4",
      name: "Bank Core",
      segment: "Protected Zone",
      assets: 34,
      critical: 14,
      status: "Критичный контур",
    },
    {
      id: "env-5",
      name: "Office Network",
      segment: "Corporate",
      assets: 42,
      critical: 3,
      status: "Под наблюдением",
    },
  ],
};

export const organizationSettings = {
  "org-1": {
    retention: "12 месяцев",
    exportDefault: "PDF и Excel",
    timezone: "Europe/Moscow",
    scanMode: "Полный",
    notifications: "Email + Dashboard",
  },
  "org-2": {
    retention: "6 месяцев",
    exportDefault: "PDF",
    timezone: "Europe/Moscow",
    scanMode: "Полный + конфигурационный",
    notifications: "Dashboard",
  },
  "org-3": {
    retention: "24 месяца",
    exportDefault: "PDF и Excel",
    timezone: "Asia/Almaty",
    scanMode: "Критичные активы + полный weekly",
    notifications: "Email + Dashboard + Telegram",
  },
};

export const organizationSoftware = {
  "org-1": [
    {
      id: "sw-1",
      name: "Nginx",
      version: "1.24.0",
      vendor: "F5",
      category: "Web Server",
      type: "Infrastructure",
      host: "web-prod-01",
      os: "Ubuntu 22.04",
      detectedAt: "2026-03-30",
    },
    {
      id: "sw-2",
      name: "PostgreSQL",
      version: "15.3",
      vendor: "PostgreSQL Global Development Group",
      category: "Database",
      type: "Infrastructure",
      host: "db-core-01",
      os: "Ubuntu 22.04",
      detectedAt: "2026-03-30",
    },
    {
      id: "sw-3",
      name: "OpenSSH",
      version: "9.0p1",
      vendor: "OpenBSD",
      category: "Access",
      type: "System",
      host: "jump-01",
      os: "Ubuntu 22.04",
      detectedAt: "2026-03-30",
    },
  ],
  "org-2": [
    {
      id: "sw-4",
      name: "HAProxy",
      version: "2.8.5",
      vendor: "HAProxy Technologies",
      category: "Proxy",
      type: "Infrastructure",
      host: "api-gw-01",
      os: "Debian 12",
      detectedAt: "2026-03-30",
    },
    {
      id: "sw-5",
      name: "Redis",
      version: "7.2",
      vendor: "Redis",
      category: "Cache",
      type: "Infrastructure",
      host: "cache-01",
      os: "Debian 12",
      detectedAt: "2026-03-30",
    },
  ],
  "org-3": [
    {
      id: "sw-6",
      name: "Oracle Database",
      version: "19c",
      vendor: "Oracle",
      category: "Database",
      type: "Critical",
      host: "core-bank-01",
      os: "Oracle Linux",
      detectedAt: "2026-03-30",
    },
    {
      id: "sw-7",
      name: "Apache Kafka",
      version: "3.7",
      vendor: "Apache",
      category: "Messaging",
      type: "Critical",
      host: "mq-01",
      os: "RHEL 9",
      detectedAt: "2026-03-30",
    },
    {
      id: "sw-8",
      name: "Zabbix Agent",
      version: "7.0",
      vendor: "Zabbix",
      category: "Monitoring",
      type: "Agent",
      host: "office-node-04",
      os: "Windows Server 2022",
      detectedAt: "2026-03-30",
    },
  ],
};